project:
  render: 
      - index.qmd
      - materials.qmd
      - schedule.qmd
      - slides.qmd
  type: website
  output-dir: docs

website:
  title: "Economia do Setor Público"
  sidebar:
    background: "#FF6961"
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/joaopedro-fg/setor-publico-24
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Cronograma
      - href: materials.qmd
        text: Materiais
      - href: mailto:joaopedrofg@usp.br
        text: Contato

format:
  html:
    theme: Journal
    # css: styles.css
    toc: true

execute:
  freeze: auto

