project:
  render: 
      - index.qmd
      - materials.qmd
      - schedule.qmd
      - slides.qmd
  type: website
  output-dir: docs

website:
  title: "<b>Economia do Setor Público</b>"
  sidebar:
    background: "#FF6961"
    foreground: light
    search: False
    # logo: "images/logo.png"
    pinned: true
    align: center
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Cronograma
      - href: materials.qmd
        text: Materiais

format:
  html:
    theme: Journal
    # css: styles.css
    toc: true

execute:
  freeze: auto

